### ISSUE TITLE
Date range picker

### ISSUE THREAD

**Issue by EstiT** [denniscm190/stock-charts#20]
It's frustrating when we can't zoom in and see more precise details for smaller/larger time periods.

I'd like to be able to zoom in to specific time ranges and scroll sideways to view more. The trades demo Details view looks like it has this feature but the picker is not actually implemented. When different ranges are selected, nothing happens. 
<img width="210" alt="Screen Shot 2021-09-29 at 6 53 03 pm" src="https://user-images.githubusercontent.com/17136826/135241159-a23e85c0-4ca0-4b23-bcff-753ec2524320.png">
https://github.com/denniscm190/trades-demo/blob/main/Trades/Details.swift#L44

**Comment by denniscm190** [comment]
Hello EstiT,
Currently, you cannot zoom in/out with gestures but you can update the chart to show a specific time frame. This is something you have to implement by your own since it's out of the scope of this framework. However, I'll try to help you:

- Add a [picker](https://developer.apple.com/documentation/swiftui/picker)
- Add `.onChange(of:perform:)` [modifier](https://developer.apple.com/documentation/swiftui/view/onchange(of:perform:))
- Implement a function that updates your `@State` variable that feeds your chart when the value that you captured with the `.onChange(of:perform:)` changes.
